version: '3.1'
services:
  jd2:
    network_mode: "host"
    image: plusminus/jdownloader2-headless
    environment:
      UID: ${UID}
      GID: ${GID}
    volumes:
       - ${JD2_CONFIG}:/opt/JDownloader/cfg
       - ${MYPLEX_MOVIE}:/downloads/movie
       - ${MYPLEX_TV}:/downloads/tv
       - ${MYPLEX_ANIME}:/downloads/anime
       - ${MYPLEX_MOVIE_AR}:/downloads/movie_ar
  plex:
    network_mode: "host"
    image: linuxserver/plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      VERSION: 'latest'
      PUID: ${UID}
      PGID: ${GID}
    volumes:
       - ${MYPLEX_CONFIG}:/config
       - ${MYPLEX_TV}:/data/tvshows
       - ${MYPLEX_MOVIE}:/data/movies
       - ${MYPLEX_ANIME}:/data/anime
       - ${MYPLEX_CARTOON_AR}:/data/cartoon_ar
       - ${MYPLEX_MOVIE_AR}:/data/movies_ar


# docker run -d --name jd2 -v /home/bhefny/jd2_config:/opt/JDownloader/cfg -v /home/bhefny/plex_content:/downloads plusminus/jdownloader2-headless
# docker create --name=plex -p 32400:32400 -p 32400:32400/udp -p 32469:32469 -p 32469:32469/udp -p 5353:5353/udp -p 1900:1900/udp -e VERSION=latest \
# -e PUID=1000 -e PGID=1000 -v /home/bhefny/plex_content/files:/config -v /home/bhefny/plex_content/tv:/data/tvshows \
# -v /home/bhefny/plex_content/movie:/data/movies linuxserver/plex
